### ISSUE TITLE
unassigned variable g15

### ISSUE THREAD

**Issue by gregmacfarlane** [sidharthanr/macml#3]
The code does not execute due to an unassigned variable. In the `pdfmvna` function, it appears that the variable `g15` is called before it gets a value. Here is line 102 through 111 of [cdfmvna.r](https://github.com/sidharthanr/macml/blob/master/R/cdfmvna.r#L102)

```
# what do these do? 
g3 = dnorm(x)
g5 = (y-rho1*x)/rho2
g10 = g3*pnorm(g5)
g11 = g3*pnorm(y)
g12 = g10-g11
g13 = g12   
g14 = g3*(1-2*z3)
g15 = g13diag(g15) = g14 #FIXME this is unclear; the first time g15 appears
g20 = -g3
```

I've added some FIXMEs, can you check on this? Also, can you make some comments explaining what all the `g*` variables are for?

**Comment by sidharthanr** [comment]
Fixed this with the last commit. Error caused by missing semi-colon.
