### ISSUE TITLE
permutations?

### ISSUE THREAD

**Issue by gregmacfarlane** [sidharthanr/macml#7]
The `getComb` function calls `permutations()` in [this line](https://github.com/sidharthanr/macml/blob/master/R/cdfmvna.r#L337):

```
oth_dims <- permutations(ncol(oth_dims), ncol(oth_dims), oth_dims)
```

I can't find this function in any package namespace I've been using so far. There's a `combinat::permn()` function, but it takes different arguments.

**Comment by sidharthanr** [comment]
It is actually from the gtools library. What it does is take a vector and create all permutations of the vector.

> permutations(3,2,c(4,2,5))
>      [,1] [,2]
> permutations(3,3,c(4,2,5))
>      [,1] [,2] [,3]
> [1,]    2    4    5
> [2,]    2    5    4
> [3,]    4    2    5
> [4,]    4    5    2
> [5,]    5    2    4
> [6,]    5    4    2
